FROM debian:bullseye

RUN apt-get update && \
apt-get install -y \
		wget \
		php7.4 \
		php7.4-fpm \
		php7.4-mysql \
		curl \
		mariadb-client \
		&& rm -rf /var/lib/apt/lists/*

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

# Copy FPM Configuration
COPY conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf

# Copy setup script
COPY tools/setup.sh /usr/local/bin/setup.sh

EXPOSE 9000

CMD ["bash", "/usr/local/bin/setup.sh"]
